language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt" 
  - "pip install codacy-coverage"
# command to run tests
script: 
  - nosetests
  - export CODACY_PROJECT_TOKEN=b087460a24c54622a4fb6c2d2a865d42
  - nosetests ./ --with-coverage --cover-package=cloud_connector --cover-xml
  - python-codacy-coverage -r coverage.xml